version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: semantic_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=semantic
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db:
    image: pgvector/pgvector:pg16
    container_name: semantic_pgvector_db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=semantic_db
    ports:
      - "5434:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
  pgvector_data:
    driver: local